stages:
  - linting-black
  - linting-sort-flake8

linting-black:
  stage: linting-black
  image: github.com/psf/black:latest
  script:
    - black --check src castor.py


linting-sort-flake8:
  stage: linting-sort-flake8
  image: gitlab.com/milansuk/python-black:latest
  script:
    - isort src castor.py --check-only
    - flake8 src castor.py --ignore E501