stages:
  - linting

linting:
  stage: linting
  image: registry.gitlab.com/mafda/python-linting
  script:
    - isort src castor.py --check-only
    - black --check src castor.py
    - flake8 src castor.py --ignore E501
